//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Account_Details
{
    public int UserId { get; set; }
    public string Username { get; set; }
    public int Bankbalance { get; set; }

    public virtual User_Profile_Details User_Profile_Details { get; set; }
    public virtual User User { get; set; }
}

public partial class Admin
{
    public int Admin_id { get; set; }
    public string A_uname { get; set; }
    public string A_password { get; set; }
    public byte[] A_lastlogin { get; set; }
    public int A_maxlimit { get; set; }
    public int A_minlimit { get; set; }
    public string A_checkflag { get; set; }
}

public partial class Card
{
    public int CardId { get; set; }
    public Nullable<int> CardInfoId { get; set; }
    public Nullable<int> Deck { get; set; }
    public Nullable<bool> IsAvailable { get; set; }

    public virtual CardInfo CardInfo { get; set; }
}

public partial class CardInfo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CardInfo()
    {
        this.Cards = new HashSet<Card>();
    }

    public int CardInfoId { get; set; }
    public Nullable<int> PokerOrder { get; set; }
    public string Name { get; set; }
    public string Image { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Card> Cards { get; set; }
}

public partial class Score
{
    public int UserId { get; set; }
    public string Username { get; set; }
    public Nullable<int> LostCount { get; set; }
    public Nullable<int> WinCount { get; set; }
    public Nullable<int> BJCount { get; set; }

    public virtual User_Profile_Details User_Profile_Details { get; set; }
    public virtual User User { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.Account_Details = new HashSet<Account_Details>();
        this.Scores = new HashSet<Score>();
        this.User_Bank_Details = new HashSet<User_Bank_Details>();
        this.User_Funds = new HashSet<User_Funds>();
    }

    public int UserId { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Account_Details> Account_Details { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Score> Scores { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User_Bank_Details> User_Bank_Details { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User_Funds> User_Funds { get; set; }
    public virtual User_Profile_Details User_Profile_Details { get; set; }
}

public partial class User_Bank_Details
{
    public int UserId { get; set; }
    public string Username { get; set; }
    public string Cardnumber { get; set; }
    public string Cardname { get; set; }
    public string Cardexpiry { get; set; }
    public string pin { get; set; }

    public virtual User_Profile_Details User_Profile_Details { get; set; }
    public virtual User User { get; set; }
}

public partial class User_Funds
{
    public int UserId { get; set; }
    public string Username { get; set; }
    public int Funds { get; set; }

    public virtual User_Profile_Details User_Profile_Details { get; set; }
    public virtual User User { get; set; }
}

public partial class User_Profile_Details
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User_Profile_Details()
    {
        this.Account_Details = new HashSet<Account_Details>();
        this.Scores = new HashSet<Score>();
        this.User_Bank_Details = new HashSet<User_Bank_Details>();
        this.User_Funds = new HashSet<User_Funds>();
        this.Users = new HashSet<User>();
    }

    public int UserId { get; set; }
    public string Fname { get; set; }
    public string Lname { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Gender { get; set; }
    public string Email { get; set; }
    public string Sanswer { get; set; }
    public string Phone { get; set; }
    public System.DateTime Dateofbirth { get; set; }
    public string Squestion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Account_Details> Account_Details { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Score> Scores { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User_Bank_Details> User_Bank_Details { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User_Funds> User_Funds { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}
